name: Terraform apply on edited folder
on:
  push:
    branches:
      - main

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [terraform-aws-ec2-instance, terraform-aws-s3-bucket]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        
        # To compare changes between the current commit and the last pushed remote commit, set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List changed files in specific folder
        run: |
          echo "Changed files in ${{ matrix.folder }}:"
          folder_modified=false
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *"${{ matrix.folder }}"* ]]; then
              echo "$file"
              folder_modified=true
              echo "FOLDER MODIFIED = $folder_modified";
            fi
          done

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: v1.4.4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      
      - name: Terraform Init
        if: env.folder_modified == 'true'
        run: |
          cd ./${{ matrix.folder }}
          terraform init
      
      - name: Terraform Apply
        if: env.folder_modified == 'true'
        run: |
          cd ./${{ matrix.folder }}
          terraform apply -auto-approve