name: Terraform apply on changed folder
on:
  push:
    branches:
      - main

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [terraform-aws-ec2-instance, terraform-aws-s3-bucket]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      - name: Change directory to GH folder
        run: | 
          cd ${{ matrix.folder }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        
        # To compare changes between the current commit and the last pushed remote commit, set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List changed files in specific folder
        run: |
          echo "Changed files in ${{ matrix.folder }}:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *"${{ matrix.folder }}"* ]]; then
              echo "$file"
            fi
          done