on:
  push:
    branches:
      - main
jobs:
  find-jobs:
    name: Find Jobs
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v1

      - id: jobs
        uses: philips-labs/list-folders-action@v1
        with:
          path: .

  matrix:
      name: Matrix Jobs
      runs-on: ubuntu-latest
      needs: [find-jobs]
      defaults:
        run:
          working-directory: ${{ matrix.folder }}
      strategy:
        matrix:
          folder: ${{ fromJson(needs.find-jobs.outputs.folders )}}
      steps:
          - name: do something
            run: echo ${{ matrix.folder }}
