on:
  push:
    branches:
      - main
jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1

  build:
    name: "Build sub-projects"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: echo ${{ matrix.folder }}
